import { Link, NavLink } from "react-router-dom";
import { useWallet } from "../context/WalletContext";
import { hasContract, NETWORK } from "../lib/contract";
import type { Candidate, Edge, Funding, LatentAssessment, Node } from "../lib/records";
import { bps, shortAddress } from "../lib/records";
import type { ReactNode } from "react";

export function Shell({children}:{children:ReactNode}){
 const wallet=useWallet(); return <div className="app-shell"><header className="topbar"><Link className="brand" to="/"><span className="seed-mark">S</span><span>SEEDLING<small>latent public goods</small></span></Link><nav aria-label="Primary"><NavLink to="/discover">Discover</NavLink><NavLink to="/register">Register</NavLink><NavLink to="/policies">Policies</NavLink><NavLink to="/methodology">Method</NavLink><NavLink to="/status">Contract</NavLink></nav><button className="wallet" onClick={()=>void(wallet.account?wallet.switchNetwork():wallet.connect())}>{wallet.connecting?"Connecting…":wallet.account?shortAddress(wallet.account):"Connect wallet"}</button></header>{wallet.wrongNetwork&&<div className="network-alert" role="alert">Wrong network. <button onClick={()=>void wallet.switchNetwork()}>Switch to {NETWORK.name}</button></div>}{wallet.error&&<div className="wallet-alert" role="alert">{wallet.error}</div>}{!hasContract&&<div className="config-alert" role="status">LIVE CONTRACT DATA unavailable — configure <code>VITE_SEEDLING_CONTRACT_ADDRESS</code>. No demo records are mixed into this view.</div>}<main id="main">{children}</main><footer><strong>SEEDLING</strong><span>Frontend ↔ Intelligent Contract. No backend.</span><span>Protocol accounting, not token transfers.</span></footer></div>
}
export function PageHead({eyebrow,title,lede,actions}:{eyebrow:string;title:string;lede:string;actions?:ReactNode}){return <header className="page-head"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="lede">{lede}</p></div>{actions}</header>}
export function LoadState({loading,error,empty,emptyTitle="No candidates discovered yet",emptyBody="The first candidate enters through a public artifact, bound policies, and evidence—not a private database.",emptyAction,children}:{loading:boolean;error?:string;empty?:boolean;emptyTitle?:string;emptyBody?:string;emptyAction?:ReactNode;children:ReactNode}){if(loading)return <div className="state-card" role="status"><span className="spinner"/>Reading finalized contract state…</div>;if(error)return <div className="state-card error" role="alert"><strong>Contract data unavailable</strong><p>{error}</p></div>;if(empty)return <div className="state-card empty"><span className="sprout">⌁</span><h2>{emptyTitle}</h2><p>{emptyBody}</p>{emptyAction===undefined?<Link className="button" to="/register">Register the first candidate</Link>:emptyAction}</div>;return <>{children}</>}
export function StatusPill({value}:{value:string}){return <span className={`status status-${value.toLowerCase().replaceAll("_","-")}`}>{value.replaceAll("_"," ")}</span>}
export function CandidateCard({candidate}:{candidate:Candidate}){return <article className="candidate-card"><div className="card-top"><span className="type">{candidate.candidate_type.replaceAll("_"," ")}</span><StatusPill value={candidate.status}/></div><h2><Link to={`/candidates/${candidate.candidate_id}`}>{candidate.name}</Link></h2><p>{candidate.description}</p><div className="card-foot"><span>origin {candidate.origin_date}</span><span>#{candidate.candidate_id}</span></div></article>}

const signalLabels:[keyof LatentAssessment,string,string][]=[
 ["independent_reuse_bps","Independent reuse","substantive, not host count"],["uniqueness_bps","Technical uniqueness","evidence-backed"],["substitution_risk_bps","Substitution risk","higher means easier substitutes"],["maintainer_health_bps","Maintainer health","continuity signal"],["ecosystem_positioning_bps","Ecosystem position","infrastructure potential"],["gaming_risk_bps","Gaming risk","higher means less trustworthy"],
];
export function LatentSignals({assessment}:{assessment:LatentAssessment}){return <section className="signal-panel"><div className="section-title"><div><p className="eyebrow">GENLAYER ADJUDICATION</p><h2>Latent significance</h2></div><div className="orb" style={{"--score":`${bps(assessment.latent_value_bps)}%`} as React.CSSProperties}><strong>{Math.round(bps(assessment.latent_value_bps))}</strong><span>potential</span></div></div><p className="muted">Forward-looking evidence about unusual infrastructure potential—not realized public value.</p><div className="signals">{signalLabels.map(([key,label,note])=><div className="signal" key={key}><div><strong>{label}</strong><small>{note}</small></div><div className="track"><span style={{width:`${bps(assessment[key] as number)}%`}}/></div><b>{Math.round(bps(assessment[key] as number))}</b></div>)}</div></section>}
export function ImpactPanel({status,latest}:{status:string;latest?:Record<string,unknown>}){return <section className="impact-panel"><p className="eyebrow">OBSERVED REALITY</p><h2>Current impact</h2><div className="impact-word">{status}</div><p>{latest?"Latest checkpoint verdict reflects demonstrated public use.":"No realized-impact verdict has been finalized yet."}</p></section>}
export function LineageGraph({nodes,edges}:{nodes:Node[];edges:Edge[]}){return <div className="lineage-wrap" aria-label="Contribution lineage graph"><div className="lineage-grid">{nodes.map((node,i)=><div className="lineage-node" key={node.node_id}><span className="node-index">{String(i+1).padStart(2,"0")}</span><strong>{node.role.replaceAll("_"," ")}</strong><small>{shortAddress(node.contributor)}</small><p>{node.summary}</p></div>)}</div>{edges.length>0&&<div className="edge-list">{edges.map(edge=><div key={edge.edge_id}><span>Node {edge.from_node_id}</span><b>— {edge.relationship_type.replaceAll("_"," ")} →</b><span>Node {edge.to_node_id}</span><small>claimed {(edge.claimed_strength_bps/100).toFixed(0)}%</small></div>)}</div>}</div>}
export function FundingTimeline({items}:{items:Funding[]}){return <div className="funding-timeline">{items.map((item,i)=><div className="funding-step" key={item.funding_calculation_id}><span className="dot"/><div><small>CHECKPOINT {item.checkpoint_id}</small><strong>{item.impact_tier}</strong><p>+{item.newly_unlocked_funding.toLocaleString()} accounting units</p></div><b>{item.target_cumulative_funding.toLocaleString()}<small> cumulative</small></b>{i<items.length-1&&<span className="stem"/>}</div>)}</div>}
export function TxBanner(){const {tx}=useWallet();if(tx.phase==="idle")return null;return <div className={`tx-banner tx-${tx.phase}`} role={tx.phase==="failed"||tx.phase==="rejected"?"alert":"status"}><strong>{tx.phase.toUpperCase()}</strong><span>{tx.message}</span>{tx.hash&&<code>{shortAddress(tx.hash)}</code>}</div>}
