import { useEffect, useState, type FormEvent, type ReactNode } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { useWallet } from "../context/WalletContext";
import { useContractRead } from "../hooks/useContract";
import { describeReadError, readContract, writeContract, hasContract, NETWORK, type WriteMethod, type ContractArg } from "../lib/contract";
import type { Appeal, Candidate, Checkpoint, Edge, Evidence, Funding, LatentAssessment, Node, Page } from "../lib/records";
import { CandidateCard, FundingTimeline, ImpactPanel, LatentSignals, LineageGraph, LoadState, PageHead, StatusPill, TxBanner } from "../components/UI";

export function Home(){return <><section className="hero"><div className="hero-copy"><p className="eyebrow">PUBLIC INFRASTRUCTURE, BEFORE CONSENSUS NOTICES</p><h1>Fund the public goods nobody knew were public goods <em>yet.</em></h1><p>SEEDLING watches obscure contributions mature, preserves their forgotten lineage, and unlocks recognition only as public value becomes real.</p><div className="hero-actions"><Link className="button primary" to="/discover">Explore candidates</Link><Link className="button ghost" to="/methodology">How it works</Link></div></div><div className="growth-map" aria-label="Protocol progression"><span className="soil">UNKNOWN<small>public artifact</small></span><i/><span>LATENT<small>GenLayer signal</small></span><i/><span>WATCHING<small>frozen checkpoints</small></span><i/><span className="canopy">SYSTEMIC<small>progressive recognition</small></span></div></section><section className="thesis-grid"><article><b>01</b><h2>Notice what is overlooked</h2><p>Permissionless discovery starts with compact public evidence, never private ranking.</p></article><article><b>02</b><h2>Separate potential from impact</h2><p>Latent significance asks what could matter. Checkpoints ask what demonstrably does.</p></article><article><b>03</b><h2>Remember who made it possible</h2><p>Acyclic lineage and evidence-based attribution keep foundational creators visible.</p></article></section><section className="flow-band"><p className="eyebrow">THE SEEDLING LOOP</p><div>{["Unknown project","Evidence accumulates","Latent signal","Impact emerges","Lineage resolves","Funding unlocks"].map((x,i)=><span key={x}><b>{i+1}</b>{x}</span>)}</div></section></>}

export function Discover(){const q=useContractRead<Page<Candidate>>("list_candidates",[0,50]);return <><PageHead eyebrow="LIVE CONTRACT DATA" title="Discover the overlooked" lede="Candidates are ordered by on-chain discovery. No popularity feed, paid placement, or hidden index." actions={<Link className="button primary" to="/register">Register candidate</Link>}/><LoadState loading={q.loading} error={q.error} empty={!q.data?.total}><div className="candidate-grid">{q.data?.items.map(c=><CandidateCard key={c.candidate_id} candidate={c}/>)}</div></LoadState></>}

type Detail={candidate:Candidate;latent?:LatentAssessment;checkpoints:Checkpoint[];evidence:Evidence[];nodes:Node[];edges:Edge[];funding:Funding[];appeals:Appeal[]};
export function CandidateDetail(){const {candidateId=""}=useParams();const [state,setState]=useState<{data?:Detail;loading:boolean;error?:string}>({loading:true});
 useEffect(()=>{let live=true;(async()=>{try{const candidate=await readContract<Candidate>("get_candidate",[candidateId]);const [checkpoints,evidence,nodes,edges,funding,appeals]=await Promise.all([readContract<Page<Checkpoint>>("list_checkpoints",[candidateId,0,50]),readContract<Page<Evidence>>("list_candidate_evidence",[candidateId,0,50]),readContract<Page<Node>>("list_contribution_nodes",[candidateId,0,50]),readContract<Page<Edge>>("list_lineage_edges",[candidateId,0,50]),readContract<Page<Funding>>("list_candidate_funding_calculations",[candidateId,0,50]),readContract<Page<Appeal>>("list_candidate_appeals",[candidateId,0,50])]);let latent:LatentAssessment|undefined;if(candidate.latent_assessment_id)latent=await readContract<LatentAssessment>("get_latent_assessment",[candidate.latent_assessment_id]);if(live)setState({loading:false,data:{candidate,latent,checkpoints:checkpoints.items,evidence:evidence.items,nodes:nodes.items,edges:edges.items,funding:funding.items,appeals:appeals.items}});}catch(e){if(live)setState({loading:false,error:describeReadError("get_candidate",[candidateId],e)});}})();return()=>{live=false};},[candidateId]);
 return <LoadState loading={state.loading} error={state.error}>{state.data&&<><PageHead eyebrow={`CANDIDATE #${candidateId}`} title={state.data.candidate.name} lede={state.data.candidate.description} actions={<StatusPill value={state.data.candidate.status}/>}/><div className="meta-strip"><a href={state.data.candidate.primary_artifact_url} target="_blank" rel="noreferrer">Public artifact ↗</a><span>{state.data.candidate.candidate_type.replaceAll("_"," ")}</span><span>Origin {state.data.candidate.origin_date}</span><span>Policies O{state.data.candidate.observation_policy_id} / F{state.data.candidate.funding_policy_id}</span></div><div className="dual-metric">{state.data.latent?<LatentSignals assessment={state.data.latent}/>:<section className="signal-panel"><h2>Latent significance</h2><p>Awaiting frozen evidence and GenLayer adjudication.</p></section>}<ImpactPanel status={state.data.candidate.status} latest={state.data.checkpoints.at(-1) as unknown as Record<string,unknown>}/></div><Section title="Evidence ledger" action={<Link to={`/candidates/${candidateId}/evidence`}>Submit evidence →</Link>}><div className="evidence-list">{state.data.evidence.length?state.data.evidence.map(e=><article key={e.evidence_id}><StatusPill value={e.status}/><strong>{e.source_type.replaceAll("_"," ")}</strong><p>{e.summary}</p><a href={e.source_url} target="_blank" rel="noreferrer">{e.source_host} ↗</a></article>):<p className="muted">No latent evidence records yet.</p>}</div></Section><Section title="Impact checkpoints" action={<Link to={`/candidates/${candidateId}/checkpoints`}>Manage checkpoints →</Link>}><div className="checkpoint-row">{state.data.checkpoints.length?state.data.checkpoints.map(cp=><Link to={`/candidates/${candidateId}/checkpoints/${cp.checkpoint_id}`} key={cp.checkpoint_id}><small>#{cp.checkpoint_id}</small><StatusPill value={cp.status}/><b>{cp.evidence_count} evidence</b></Link>):<p className="muted">No impact observation periods yet.</p>}</div></Section><Section title="Foundational lineage" action={<Link to={`/candidates/${candidateId}/lineage`}>Open explorer →</Link>}><LineageGraph nodes={state.data.nodes} edges={state.data.edges}/></Section><div className="two-col"><Section title="Dormant funding"><FundingTimeline items={state.data.funding}/><Link to={`/candidates/${candidateId}/funding`}>Full funding history →</Link></Section><Section title="Appeals & finality"><p>{state.data.appeals.length} appeal record(s)</p><Link to={`/candidates/${candidateId}/appeals`}>Inspect appeals →</Link></Section></div></>}</LoadState>}

function Section({title,action,children}:{title:string;action?:ReactNode;children:ReactNode}){return <section className="content-section"><div className="section-title"><h2>{title}</h2>{action}</div>{children}</section>}

function useTx(){const wallet=useWallet();async function submit(method:WriteMethod,args:ContractArg[]){if(!wallet.account||!wallet.provider)throw new Error("Connect a wallet first.");if(wallet.wrongNetwork)throw new Error(`Switch to ${NETWORK.name} first.`);return writeContract(wallet.account,wallet.provider,method,args,wallet.setTx);}return {wallet,submit}}

export function Register(){const {wallet,submit}=useTx();const navigate=useNavigate();const [error,setError]=useState<string>();async function onSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError(undefined);const f=new FormData(e.currentTarget);const args:ContractArg[]=["name","description","candidate_type","primary_artifact_url","origin_date"].map(k=>String(f.get(k)));args.push(true,String(f.get("observation_policy_id")),String(f.get("funding_policy_id")));try{await submit("register_candidate",args);navigate("/discover");}catch(x){setError(x instanceof Error?x.message:"Registration failed.");}}
 return <><PageHead eyebrow="PERMISSIONLESS DISCOVERY" title="Register an overlooked contribution" lede="Bind the candidate to immutable observation and funding policy versions. Registration is a claim, not an endorsement."/><TxBanner/><form className="protocol-form" onSubmit={e=>void onSubmit(e)}><Field name="name" label="Project name" required maxLength={120}/><Field name="description" label="Why might this matter?" textarea required maxLength={2000}/><label>Candidate type<select name="candidate_type"><option>OPEN_SOURCE_LIBRARY</option><option>DATASET</option><option>RESEARCH</option><option>DOCUMENTATION</option><option>DEVELOPER_TOOL</option><option>PUBLIC_ARCHIVE</option><option>COMMUNITY_INFRASTRUCTURE</option><option>PROTOCOL_COMPONENT</option><option>EDUCATIONAL_RESOURCE</option><option>CUSTOM</option></select></label><Field name="primary_artifact_url" label="Public artifact URL" type="url" required/><Field name="origin_date" label="Origin date" placeholder="YYYY-MM-DD" required/><div className="form-row"><Field name="observation_policy_id" label="Observation policy ID" required/><Field name="funding_policy_id" label="Funding policy ID" required/></div>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button primary" disabled={!wallet.account||wallet.wrongNetwork}>Submit registration</button>{!wallet.account&&<p className="hint">Connect a StudioNet wallet to submit.</p>}</form></>}

function Field(props:{name:string;label:string;textarea?:boolean;type?:string;required?:boolean;maxLength?:number;placeholder?:string}){const {label,textarea,...rest}=props;return <label>{label}{textarea?<textarea {...rest}/>:<input {...rest}/>}</label>}

export function EvidencePage(){const {candidateId=""}=useParams();const q=useContractRead<Page<Evidence>>("list_candidate_evidence",[candidateId,0,50]);const {submit}=useTx();const [error,setError]=useState<string>();async function send(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await submit("submit_candidate_evidence",[candidateId,String(f.get("type")),String(f.get("url")),String(f.get("hash")),String(f.get("summary")),Number(f.get("start")),Number(f.get("end"))]);await q.refresh();}catch(x){setError(x instanceof Error?x.message:"Submission failed.");}}return <><PageHead eyebrow="PUBLIC EVIDENCE" title="Candidate evidence" lede="Only compact URL, digest, period, and bounded metadata are stored. Page content remains off-chain and untrusted."/><div className="two-col"><form className="protocol-form compact" onSubmit={e=>void send(e)}><label>Evidence category<select name="type"><option>SOURCE_REPOSITORY</option><option>PACKAGE_REGISTRY</option><option>DEPENDENCY_GRAPH</option><option>DOWNSTREAM_REPOSITORY</option><option>PUBLIC_USAGE_RECORD</option><option>RESEARCH_CITATION</option></select></label><Field name="url" label="Public URL" type="url" required/><Field name="hash" label="Content digest" required/><Field name="summary" label="Bounded summary" textarea required maxLength={1000}/><div className="form-row"><Field name="start" label="Period start (Unix)" type="number" required/><Field name="end" label="Period end (Unix)" type="number" required/></div>{error&&<p role="alert" className="form-error">{error}</p>}<button className="button primary">Submit evidence</button></form><LoadState loading={q.loading} error={q.error} empty={!q.data?.total} emptyTitle="No evidence submitted yet" emptyBody="Evidence is a public URL, a content digest, and a bounded period. Nothing here is inferred or back-filled." emptyAction={null}><div className="evidence-list">{q.data?.items.map(e=><article key={e.evidence_id}><StatusPill value={e.status}/><strong>{e.source_type}</strong><p>{e.summary}</p></article>)}</div></LoadState></div></>}

export function CheckpointsPage(){const {candidateId=""}=useParams();const q=useContractRead<Page<Checkpoint>>("list_checkpoints",[candidateId,0,50]);return <><PageHead eyebrow="LONGITUDINAL OBSERVATION" title="Impact checkpoints" lede="Each bounded period freezes its own evidence before GenLayer judges realized public value."/><LoadState loading={q.loading} error={q.error} empty={!q.data?.total} emptyTitle="No observation periods yet" emptyBody="Each checkpoint freezes its own evidence before GenLayer judges realized public value." emptyAction={null}><div className="checkpoint-table">{q.data?.items.map(cp=><Link key={cp.checkpoint_id} to={`/candidates/${candidateId}/checkpoints/${cp.checkpoint_id}`}><b>Checkpoint {cp.checkpoint_id}</b><span>{new Date(cp.period_start*1000).toLocaleDateString()} — {new Date(cp.period_end*1000).toLocaleDateString()}</span><StatusPill value={cp.status}/></Link>)}</div></LoadState></>}
export function CheckpointDetail(){const {candidateId="",checkpointId=""}=useParams();const cp=useContractRead<Checkpoint>("get_checkpoint",[checkpointId]);const evidence=useContractRead<Page<Evidence>>("list_checkpoint_evidence",[checkpointId,0,50]);return <><PageHead eyebrow={`CANDIDATE #${candidateId}`} title={`Checkpoint ${checkpointId}`} lede="Submission, consensus adjudication, lineage, funding, appeal, and finalization remain distinct states." actions={cp.data&&<StatusPill value={cp.data.status}/>}/><LoadState loading={cp.loading||evidence.loading} error={cp.error||evidence.error}><div className="two-col"><Section title="Frozen observation window"><p>{cp.data&&`${new Date(cp.data.period_start*1000).toLocaleString()} — ${new Date(cp.data.period_end*1000).toLocaleString()}`}</p><p>{cp.data?.evidence_count} compact evidence references</p></Section><Section title="Lifecycle IDs"><dl><dt>Impact verdict</dt><dd>{cp.data?.impact_verdict_id||"pending"}</dd><dt>Lineage verdict</dt><dd>{cp.data?.lineage_verdict_id||"pending"}</dd><dt>Appeal</dt><dd>{cp.data?.appeal_id||"none"}</dd></dl></Section></div><div className="evidence-list">{evidence.data?.items.map(e=><article key={e.evidence_id}><strong>{e.source_type}</strong><p>{e.summary}</p><a href={e.source_url} target="_blank" rel="noreferrer">{e.source_host} ↗</a></article>)}</div></LoadState></>}

export function LineagePage(){const {candidateId=""}=useParams();const nodes=useContractRead<Page<Node>>("list_contribution_nodes",[candidateId,0,50]);const edges=useContractRead<Page<Edge>>("list_lineage_edges",[candidateId,0,50]);return <><PageHead eyebrow="HISTORICAL ATTRIBUTION" title="Lineage explorer" lede="Claims form an acyclic provenance graph. GenLayer—not role labels or edge strength—adjudicates causal attribution."/><LoadState loading={nodes.loading||edges.loading} error={nodes.error||edges.error} empty={!nodes.data?.total} emptyTitle="No lineage claims yet" emptyBody="Contribution nodes and edges are append-only claims, not attribution proof." emptyAction={null}><LineageGraph nodes={nodes.data?.items??[]} edges={edges.data?.items??[]}/><aside className="callout">A downstream project may become famous while its foundational ancestor remains attributable. Every edge is evidence-supported, but still only a claim until adjudication.</aside></LoadState></>}
export function FundingPage(){const {candidateId=""}=useParams();const q=useContractRead<Page<Funding>>("list_candidate_funding_calculations",[candidateId,0,50]);return <><PageHead eyebrow="PROTOCOL ACCOUNTING" title="Dormant funding progression" lede="Each checkpoint unlocks only the incremental policy-permitted amount. These are accounting units—not transferred tokens."/><LoadState loading={q.loading} error={q.error} empty={!q.data?.total} emptyTitle="No funding calculated yet" emptyBody="Recognition unlocks only after a checkpoint is adjudicated under its bound funding policy." emptyAction={null}><FundingTimeline items={q.data?.items??[]}/></LoadState></>}
export function AppealsPage(){const {candidateId=""}=useParams();const q=useContractRead<Page<Appeal>>("list_candidate_appeals",[candidateId,0,50]);return <><PageHead eyebrow="CONTESTABLE, THEN FINAL" title="Appeals" lede="Original verdicts remain immutable. UPHOLD, MODIFY, or VOID creates an explicit effective result before irreversible finalization."/><LoadState loading={q.loading} error={q.error} empty={!q.data?.total} emptyTitle="No appeals filed" emptyBody="Verdicts stay contestable until a checkpoint is irreversibly finalized." emptyAction={null}><div className="appeal-list">{q.data?.items.map(a=><article key={a.appeal_id}><div><b>Appeal {a.appeal_id}</b><StatusPill value={a.status}/></div><h2>{a.ground.replaceAll("_"," ")}</h2><p>{a.statement}</p><strong>{a.decision||"Awaiting adjudication"}</strong></article>)}</div></LoadState></>}

export function Methodology(){return <><PageHead eyebrow="PROTOCOL METHODOLOGY" title="Potential is not proof. Popularity is not public value." lede="SEEDLING combines substantive GenLayer judgment with deterministic storage, lifecycle, and funding invariants."/><div className="method-grid"><Section title="Latent significance"><p>Forward-looking assessment of early reuse, uniqueness, substitutes, maintainer health, experimentation, accessibility, and ecosystem position.</p></Section><Section title="Current impact"><p>Checkpoint-specific realized adoption, persistence, dependency importance, replacement difficulty, and manipulation risk.</p></Section><Section title="Comparative consensus"><p>Frozen evidence → bounded public rendering → explicit criteria → independent comparative validators → exact schema → write-once record.</p></Section><Section title="Progressive recognition"><p>Deterministic policy caps and cumulative accounting prevent raw model output, replay, or fame from producing a maximum unlock.</p></Section></div></>}
export function ContractStatus(){const q=useContractRead<Record<string,unknown>>("get_protocol_info",[]);return <><PageHead eyebrow="DIRECT CONTRACT INTEGRATION" title="Protocol status" lede="The browser talks directly to the configured Intelligent Contract. No proxy, indexer, or canonical off-chain cache."/><div className="status-board"><div><small>NETWORK</small><strong>{NETWORK.name}</strong><span>chain {NETWORK.id}</span></div><div><small>CONTRACT</small><strong>{hasContract?"Configured":"Required"}</strong><span>{hasContract?"LIVE CONTRACT DATA":"Set VITE_SEEDLING_CONTRACT_ADDRESS"}</span></div><div><small>ABI</small><strong>56 methods</strong><span>33 views / 23 writes</span></div></div><LoadState loading={q.loading} error={q.error}><pre className="json-view">{JSON.stringify(q.data,null,2)}</pre></LoadState></>}
