import { render, screen } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { describe, expect, it } from "vitest";
import { CandidateCard, FundingTimeline, LineageGraph } from "../components/UI";
import { assertWriteOrder, describeReadError, normalizeContractResult } from "../lib/contract";
import css from "../styles.css?raw";

describe("routing-ready product components",()=>{
 it("renders a live candidate as a deep link",()=>{render(<MemoryRouter><CandidateCard candidate={{candidate_id:"7",name:"Quiet Parser",description:"Foundational parser",candidate_type:"DEVELOPER_TOOL",primary_artifact_url:"https://example.com",origin_date:"2026",public_access:true,observation_policy_id:"1",funding_policy_id:"1",status:"WATCHING"}}/></MemoryRouter>);expect(screen.getByRole("link",{name:"Quiet Parser"})).toHaveAttribute("href","/candidates/7");expect(screen.getByText("WATCHING")).toBeInTheDocument();});
 it("renders lineage direction and forgotten contributor address",()=>{render(<LineageGraph nodes={[{node_id:"1",contributor:"0x1111111111111111111111111111111111111111",artifact_type:"SOURCE_CODE",artifact_url:"https://a.example",role:"ORIGINAL_AUTHOR",summary:"Original primitive"},{node_id:"2",contributor:"0x2222222222222222222222222222222222222222",artifact_type:"SOURCE_CODE",artifact_url:"https://b.example",role:"FORK_MAINTAINER",summary:"Later fork"}]} edges={[{edge_id:"1",from_node_id:"2",to_node_id:"1",relationship_type:"FORKED_FROM",claimed_strength_bps:9000}]}/>);expect(screen.getByText(/FORKED FROM/)).toBeInTheDocument();expect(screen.getByText("0x1111…1111")).toBeInTheDocument();});
 it("renders progressive accounting without claiming token transfers",()=>{render(<FundingTimeline items={[{funding_calculation_id:"1",checkpoint_id:"1",impact_tier:"WATCHING",target_cumulative_funding:500,previously_recognized_funding:0,newly_unlocked_funding:500,status:"CALCULATED"},{funding_calculation_id:"2",checkpoint_id:"2",impact_tier:"MATERIAL",target_cumulative_funding:4000,previously_recognized_funding:500,newly_unlocked_funding:3500,status:"CALCULATED"}]}/>);expect(screen.getByText("+500 accounting units")).toBeInTheDocument();expect(screen.getByText("+3,500 accounting units")).toBeInTheDocument();});
 it("freezes critical ABI write ordering",()=>{expect(assertWriteOrder("register_candidate",["name","description","candidate_type","primary_artifact_url","origin_date","public_access","observation_policy_id","funding_policy_id"])).toBe(true);expect(assertWriteOrder("open_appeal",["candidate_id","checkpoint_id","ground","supporting_refs","statement"])).toBe(true);});
 it("freezes policy-creation ABI ordering",()=>{expect(assertWriteOrder("create_observation_policy",["name","candidate_types","minimum_evidence_categories","minimum_independent_sources","latent_rules","impact_rules","lineage_rules","gaming_rules","substitute_rules","checkpoint_interval"])).toBe(true);expect(assertWriteOrder("create_funding_policy",["name","latent_cap_bps","watching_cap_bps","emerging_cap_bps","material_cap_bps","systemic_cap_bps","minimum_public_value_bps","maximum_gaming_risk_bps","minimum_attribution_confidence_bps"])).toBe(true);});
 it("normalizes JSON contract reads without altering scalar returns",()=>{expect(normalizeContractResult('{"items":[],"total":0}')).toEqual({items:[],total:0});expect(normalizeContractResult("FINALIZED")).toBe("FINALIZED");});
 it("translates raw client failures into product copy without leaking internals",()=>{const viem=new Error("Missing or invalid parameters. Double check you have provided the correct parameters. Details: execution failed Version: viem@2.55.19");const message=describeReadError("get_candidate",["1"],viem);expect(message).toBe("Candidate #1 was not found on the canonical contract.");expect(message).not.toMatch(/viem/i);expect(describeReadError("list_candidates",[0,50],new Error("Failed to fetch"))).toMatch(/Could not reach StudioNet/);});
 it("keeps a sparsely filled candidate grid from painting empty tracks",()=>{const rule=css.match(/\.candidate-grid\{[^}]*\}/)?.[0]??"";expect(rule).not.toMatch(/background/);expect(rule).toContain("auto-fill");expect(css).toContain(".candidate-card{background:var(--paper);outline:1px solid var(--line)");});
 it("keeps primary navigation reachable on small screens",()=>{expect(css).not.toContain(".topbar nav{display:none}");expect(css).toContain(".topbar nav a{white-space:nowrap}");});
 it("contains responsive 375, 768, and desktop rules with overflow-safe grids",()=>{expect(css).toContain("@media(max-width:560px)");expect(css).toContain("@media(max-width:900px)");expect(css).toContain("min-width:320px");expect(css).toContain("overflow:auto");});
});
