import { render, screen } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { describe, expect, it } from "vitest";
import { CandidateCard, FundingTimeline, LineageGraph } from "../components/UI";
import { assertWriteOrder, normalizeContractResult } from "../lib/contract";
import css from "../styles.css?raw";

describe("routing-ready product components",()=>{
 it("renders a live candidate as a deep link",()=>{render(<MemoryRouter><CandidateCard candidate={{candidate_id:"7",name:"Quiet Parser",description:"Foundational parser",candidate_type:"DEVELOPER_TOOL",primary_artifact_url:"https://example.com",origin_date:"2026",public_access:true,observation_policy_id:"1",funding_policy_id:"1",status:"WATCHING"}}/></MemoryRouter>);expect(screen.getByRole("link",{name:"Quiet Parser"})).toHaveAttribute("href","/candidates/7");expect(screen.getByText("WATCHING")).toBeInTheDocument();});
 it("renders lineage direction and forgotten contributor address",()=>{render(<LineageGraph nodes={[{node_id:"1",contributor:"0x1111111111111111111111111111111111111111",artifact_type:"SOURCE_CODE",artifact_url:"https://a.example",role:"ORIGINAL_AUTHOR",summary:"Original primitive"},{node_id:"2",contributor:"0x2222222222222222222222222222222222222222",artifact_type:"SOURCE_CODE",artifact_url:"https://b.example",role:"FORK_MAINTAINER",summary:"Later fork"}]} edges={[{edge_id:"1",from_node_id:"2",to_node_id:"1",relationship_type:"FORKED_FROM",claimed_strength_bps:9000}]}/>);expect(screen.getByText(/FORKED FROM/)).toBeInTheDocument();expect(screen.getByText("0x1111…1111")).toBeInTheDocument();});
 it("renders progressive accounting without claiming token transfers",()=>{render(<FundingTimeline items={[{funding_calculation_id:"1",checkpoint_id:"1",impact_tier:"WATCHING",target_cumulative_funding:500,previously_recognized_funding:0,newly_unlocked_funding:500,status:"CALCULATED"},{funding_calculation_id:"2",checkpoint_id:"2",impact_tier:"MATERIAL",target_cumulative_funding:4000,previously_recognized_funding:500,newly_unlocked_funding:3500,status:"CALCULATED"}]}/>);expect(screen.getByText("+500 accounting units")).toBeInTheDocument();expect(screen.getByText("+3,500 accounting units")).toBeInTheDocument();});
 it("freezes critical ABI write ordering",()=>{expect(assertWriteOrder("register_candidate",["name","description","candidate_type","primary_artifact_url","origin_date","public_access","observation_policy_id","funding_policy_id"])).toBe(true);expect(assertWriteOrder("open_appeal",["candidate_id","checkpoint_id","ground","supporting_refs","statement"])).toBe(true);});
 it("normalizes JSON contract reads without altering scalar returns",()=>{expect(normalizeContractResult('{"items":[],"total":0}')).toEqual({items:[],total:0});expect(normalizeContractResult("FINALIZED")).toBe("FINALIZED");});
 it("contains responsive 375, 768, and desktop rules with overflow-safe grids",()=>{expect(css).toContain("@media(max-width:560px)");expect(css).toContain("@media(max-width:900px)");expect(css).toContain("min-width:320px");expect(css).toContain("overflow:auto");});
});
